# Generated by Django 3.2.8 on 2021-12-23 04:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_blogpost_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
