# Generated by Django 3.2.8 on 2022-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211223_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='priority',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
