# Generated by Django 3.2.8 on 2022-01-12 05:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_blogcategory_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['priority'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='priority',
            field=models.IntegerField(null=True, unique=True, verbose_name='Приоритет для показа на фронте'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
