# Generated by Django 3.2.8 on 2022-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220112_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('about_us', models.CharField(max_length=75, verbose_name='О нас')),
                ('address', models.CharField(max_length=75, verbose_name='Наш адрес')),
                ('phone_number_for_conntact', models.CharField(max_length=75, verbose_name='Номера для связи')),
            ],
            options={
                'verbose_name': 'Сервисная информация',
                'verbose_name_plural': 'Сервисные информации',
            },
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='in_main_menu',
            field=models.BooleanField(default=False, verbose_name='Показать в гл. меню'),
        ),
    ]
