# Generated by Django 3.2.8 on 2022-01-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220112_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BlogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=255, verbose_name='Записи')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('in_archive', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogcategory', verbose_name='Название записи')),
            ],
            options={
                'verbose_name': ' Запись в публикации',
                'verbose_name_plural': 'Записи в вубликации',
            },
        ),
    ]
