# Generated by Django 3.2.8 on 2022-01-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220126_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogrecord',
            options={'verbose_name': ' Запись в публикации', 'verbose_name_plural': 'Записи в публикации'},
        ),
        migrations.AlterField(
            model_name='blogrecord',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogpost', verbose_name='Название записи'),
        ),
    ]
