# Generated by Django 3.2.8 on 2022-01-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_title_blogrecord_titlerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogrecord',
            old_name='record',
            new_name='record_detail',
        ),
    ]
