# Generated by Django 3.2.8 on 2022-03-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20220305_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrecord',
            name='title',
            field=models.CharField(default='Новая запись', max_length=255, verbose_name='Название записи'),
        ),
        migrations.AlterField(
            model_name='blogrecord',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogpost', verbose_name='Имя поста'),
        ),
    ]
